# This .conf is mainly used on old version of tmux
# There may be incompabilities with newer ones

# remap prefix from 'C-b' to 'C-p'
unbind C-b
unbind C-p
bind C-p send-prefix
set -g prefix C-p

# split panes using i and u
unbind '"'
unbind %
bind i split-window -h
bind u split-window -v

# switch panes using Alt-{h,j,k,l} or Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# Ctrl , and . to switch windows (< and >)
bind -n M-, previous-window
bind -n M-. next-window

# Enable mouse mode
setw -g mode-mouse copy-mode
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on
set -g mouse-utf8 on
# Fresh tmux
# Enable mouse mode
#set -g mouse on

# Disable delay caused by ESC-as-Mod behavior
set -s escape-time 0

# Vi keybindings in select mode
setw -g mode-keys vi

# 'v' to start selection and 'y' to copy
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection
# Fresh tmux
# 'v' to start selection, 'y' to copy, 'Y' to copy line
#bind -T copy-mode-vi v send -X begin-selection
#bind -T copy-mode-vi y send -X copy-selection-and-cancel
#bind -T copy-mode-vi Y send -X copy-line
# copy to the X clipboard
#bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xsel --input --clipboard'

# Force 256 colors
# Maybe use tmux-256color on newer versions
# Also check for true color settings
set -g default-terminal "screen-256color"
